import {
  User,
  Case,
  Patient,
  TimelineEvent,
  LabProfile,
  InventoryItem,
  DoctorInventoryItem,
  OrderChat,
  ToothChartData,
  ClinicalVisit,
  OperatoryChair,
  QueueEntry,
  ConsumableItem,
  InventoryMovement,
  ClinicalInvoice,
} from '@/types';

export const mockUsers: User[] = [
  { id: 'u1', name: 'Dr. Aryan Sharma', role: 'DENTIST', avatarUrl: 'https://i.pravatar.cc/150?u=u1' },
  { id: 'u2', name: 'Advance Dental Export', role: 'LAB_ADMIN', labId: 'lab1', avatarUrl: 'https://i.pravatar.cc/150?u=u2' },
];

export const mockPatients: Patient[] = [
  {
    id: 'p1',
    dentistId: 'u1',
    name: 'Rahul Sharma',
    age: 35,
    gender: 'MALE',
    medicalHistory: 'Hypertension (Controlled on Amlodipine 5mg)',
    contactInfo: '+91 98765 43210',
    phone: '+91 98765 43210',
    email: 'rahul.sharma@example.com',
    address: 'Flat 402, Green Glen Heights, Bengaluru',
    allergies: ['Sulfa drugs'],
    medicalAlerts: ['High Blood Pressure'],
    createdAt: '2026-06-01T10:00:00Z',
    outstandingBalance: 3200,
    lastVisitDate: '2026-08-10',
  },
  {
    id: 'p2',
    dentistId: 'u1',
    name: 'Priya Singh',
    age: 28,
    gender: 'FEMALE',
    medicalHistory: 'Allergic to Penicillin & Ampicillin',
    contactInfo: '+91 91234 56789',
    phone: '+91 91234 56789',
    email: 'priya.singh@example.com',
    address: 'Indiranagar 100ft Rd, Bengaluru',
    allergies: ['Penicillin'],
    medicalAlerts: ['Penicillin Allergy'],
    createdAt: '2026-06-05T09:30:00Z',
    outstandingBalance: 0,
    lastVisitDate: '2026-08-12',
  },
  {
    id: 'p3',
    dentistId: 'u1',
    name: 'Amit Patel',
    age: 42,
    gender: 'MALE',
    medicalHistory: 'Type 2 Diabetes Mellitus (HbA1c: 6.8)',
    contactInfo: '+91 98111 22334',
    phone: '+91 98111 22334',
    email: 'amit.patel@example.com',
    address: 'Koramangala 4th Block, Bengaluru',
    allergies: [],
    medicalAlerts: ['Diabetic - Monitor Healing'],
    createdAt: '2026-06-10T08:00:00Z',
    outstandingBalance: 12500,
    lastVisitDate: '2026-08-08',
  },
  {
    id: 'p4',
    dentistId: 'u1',
    name: 'Neha Gupta',
    age: 31,
    gender: 'FEMALE',
    medicalHistory: 'Asthma (Carries Inhaler)',
    contactInfo: '+91 99887 66554',
    phone: '+91 99887 66554',
    email: 'neha.gupta@example.com',
    address: 'HSR Layout Sector 2, Bengaluru',
    allergies: ['Latex Gloves'],
    medicalAlerts: ['Asthmatic', 'Latex Sensitivity'],
    createdAt: '2026-05-20T14:20:00Z',
    outstandingBalance: 1500,
    lastVisitDate: '2026-08-01',
  },
];

// Mock Patient Tooth Charts
export const mockToothCharts: Record<string, ToothChartData> = {
  p1: {
    16: {
      condition: 'filling',
      surfaces: { B: 'healthy', M: 'healthy', O: 'filling', D: 'filling', L: 'healthy' },
      note: 'Composite Class II restored 2025',
    },
    14: {
      condition: 'crown',
      surfaces: { B: 'crown', M: 'crown', O: 'crown', D: 'crown', L: 'crown' },
      note: 'Zirconia Crown planned',
    },
    26: {
      condition: 'cavity',
      surfaces: { B: 'healthy', M: 'healthy', O: 'cavity', D: 'healthy', L: 'healthy' },
      note: 'Occlusal pit caries',
    },
    36: {
      condition: 'rct',
      surfaces: { B: 'rct', M: 'rct', O: 'rct', D: 'rct', L: 'rct' },
      note: 'Root canal treated. Recommended PFM/Zirconia crown.',
    },
    46: {
      condition: 'missing',
      surfaces: { B: 'missing', M: 'missing', O: 'missing', D: 'missing', L: 'missing' },
      note: 'Extracted in 2023. Implant site candidate.',
    },
  },
  p2: {
    11: {
      condition: 'fracture',
      surfaces: { B: 'fracture', M: 'healthy', I: 'fracture', D: 'healthy', L: 'healthy' },
      note: 'Incisal angle chip. Veneer/composite bonding needed.',
    },
    21: {
      condition: 'healthy',
      surfaces: { B: 'healthy', M: 'healthy', I: 'healthy', D: 'healthy', L: 'healthy' },
    },
    37: {
      condition: 'sealant',
      surfaces: { B: 'healthy', M: 'healthy', O: 'sealant', D: 'healthy', L: 'healthy' },
    },
    47: {
      condition: 'sealant',
      surfaces: { B: 'healthy', M: 'healthy', O: 'sealant', D: 'healthy', L: 'healthy' },
    },
  },
  p3: {
    18: {
      condition: 'unerupted',
      surfaces: { B: 'unerupted', M: 'unerupted', O: 'unerupted', D: 'unerupted', L: 'unerupted' },
      note: 'Horizontally impacted third molar',
    },
    28: {
      condition: 'missing',
      surfaces: { B: 'missing', M: 'missing', O: 'missing', D: 'missing', L: 'missing' },
    },
    30: {
      condition: 'implant',
      surfaces: { B: 'implant', M: 'implant', O: 'implant', D: 'implant', L: 'implant' },
      note: 'Nobel Biocare 4.3mm fixture with custom abutment',
    },
    48: {
      condition: 'unerupted',
      surfaces: { B: 'unerupted', M: 'unerupted', O: 'unerupted', D: 'unerupted', L: 'unerupted' },
      note: 'Mesioangular impaction with pericoronitis history',
    },
  },
  p4: {
    15: {
      condition: 'filling',
      surfaces: { B: 'healthy', M: 'filling', O: 'filling', D: 'healthy', L: 'healthy' },
    },
    46: {
      condition: 'watch',
      surfaces: { B: 'healthy', M: 'healthy', O: 'watch', D: 'healthy', L: 'healthy' },
      note: 'Incipient buccal pit stain under observation',
    },
  },
};

// Mock Clinical Visits
export const mockClinicalVisits: ClinicalVisit[] = [
  {
    id: 'v1',
    patientId: 'p1',
    dentistId: 'u1',
    visitDate: '2026-08-10',
    chiefComplaint: 'Pain on biting on lower right molar and food lodgement',
    diagnosis: 'Symptomatic Irreversible Pulpitis #36 with defective restoration',
    clinicalFindings: 'Deep disto-occlusal cavity with pulp exposure on excavation. Tender to percussion (+). Vitality test negative.',
    treatmentRendered: 'Access opening, BMP up to F2 ProTaper, copious NaOCl irrigation, and Metapaste Ca(OH)2 closed dressing placed.',
    procedures: ['Endodontic Access & Instrumentation', 'Intra-canal Medicament Placement'],
    vitals: { bp: '128/82', pulse: '74 bpm', temperature: '98.4 F', spO2: '99%' },
    prescriptions: [
      { id: 'rx1', drugName: 'Amoxicillin 500mg', dosage: '1 tablet', frequency: '1-0-1 (Twice daily after food)', duration: '5 days', instructions: 'Complete full course' },
      { id: 'rx2', drugName: 'Zerodol-SP (Aceclofenac + Paracetamol + Serratiopeptidase)', dosage: '1 tablet', frequency: '1-0-1 (Twice daily after meals)', duration: '3 days', instructions: 'Take with antacid if stomach is sensitive' },
    ],
    voiceTranscript: 'Patient examined in chair 1. Access done for 36 under 2% lignocaine with adrenaline. Found 3 canals: MB, ML, Distal. Working lengths established via apex locator. Closed dressing given.',
    status: 'COMPLETED',
    createdAt: '2026-08-10T11:00:00Z',
    updatedAt: '2026-08-10T11:45:00Z',
  },
  {
    id: 'v2',
    patientId: 'p1',
    dentistId: 'u1',
    visitDate: '2026-08-01',
    chiefComplaint: 'Upper right crown evaluation and routine checkup',
    diagnosis: 'Gingival inflammation around old PFM crown #14',
    clinicalFindings: 'Marginal discrepancy on distal aspect. Subgingival calculus present.',
    treatmentRendered: 'Subgingival ultrasonic debridement, crown margin re-preparation, digital intra-oral optical impression taken for monolithic Zirconia crown.',
    procedures: ['Crown Preparation #14', 'Digital Scan / Impression', 'Temporary Crown Placement'],
    vitals: { bp: '130/84', pulse: '78 bpm', temperature: '98.6 F' },
    prescriptions: [
      { id: 'rx3', drugName: 'Chlorhexidine 0.2% Mouthwash', dosage: '10 ml', frequency: 'Twice daily', duration: '7 days', instructions: 'Rinse for 60 seconds without water' },
    ],
    linkedCaseId: 'c1',
    status: 'COMPLETED',
    createdAt: '2026-08-01T10:30:00Z',
    updatedAt: '2026-08-01T11:20:00Z',
  },
  {
    id: 'v3',
    patientId: 'p2',
    dentistId: 'u1',
    visitDate: '2026-08-12',
    chiefComplaint: 'Chipped front tooth while playing sports',
    diagnosis: 'Ellis Class II Enamel-Dentin Fracture #11 without pulpal involvement',
    clinicalFindings: 'Incisal mesial third fractured. Normal response on electric pulp tester. No mobility.',
    treatmentRendered: 'Selective enamel beveling, rubber dam isolation, 37% phosphoric acid etching, single bond Universal adhesive, and multi-layer composite resin aesthetic build-up (Shade A2 Body + Enamel Translucent).',
    procedures: ['Direct Composite Aesthetic Bonding #11', 'Finishing & Polishing (Sof-Lex)'],
    vitals: { bp: '116/76', pulse: '68 bpm', temperature: '98.2 F' },
    prescriptions: [],
    status: 'COMPLETED',
    createdAt: '2026-08-12T15:00:00Z',
    updatedAt: '2026-08-12T15:55:00Z',
  },
];

// Mock Operatory Chairs for Flow Board
export const mockChairs: OperatoryChair[] = [
  {
    id: 'chair1',
    name: 'Operatory 1 (Prostho / Restorative)',
    roomNumber: 'OP-01',
    status: 'OCCUPIED',
    currentPatientId: 'p1',
    currentPatientName: 'Rahul Sharma',
    currentProcedure: 'Root Canal Obturation #36',
    occupiedSince: '10:15 AM',
    doctorName: 'Dr. Aryan Sharma',
  },
  {
    id: 'chair2',
    name: 'Operatory 2 (Surgical & Implant Suite)',
    roomNumber: 'OP-02',
    status: 'AVAILABLE',
    doctorName: 'Dr. Aryan Sharma',
  },
  {
    id: 'chair3',
    name: 'Operatory 3 (Orthodontics & Preventive)',
    roomNumber: 'OP-03',
    status: 'CLEANING',
    currentProcedure: 'Sterilization & Cavicide Decontamination',
    occupiedSince: '10:45 AM',
    doctorName: 'Staff Nurse Rekha',
  },
];

// Mock Queue Entries
export const mockQueue: QueueEntry[] = [
  {
    id: 'q1',
    patientId: 'p1',
    patientName: 'Rahul Sharma',
    patientPhone: '+91 98765 43210',
    dentistId: 'u1',
    doctorName: 'Dr. Aryan Sharma',
    scheduledTime: '10:00 AM',
    checkInTime: '09:50 AM',
    waitingMinutes: 25,
    stage: 'IN_CHAIR',
    chairId: 'chair1',
    chairName: 'Operatory 1',
    treatmentType: 'RCT Obturation #36',
    notes: 'Pre-op IOPA confirmed working lengths',
  },
  {
    id: 'q2',
    patientId: 'p3',
    patientName: 'Amit Patel',
    patientPhone: '+91 98111 22334',
    dentistId: 'u1',
    doctorName: 'Dr. Aryan Sharma',
    scheduledTime: '10:30 AM',
    checkInTime: '10:20 AM',
    waitingMinutes: 15,
    stage: 'WAITING',
    treatmentType: 'Implant Crown Try-in #30',
    notes: 'Diabetic - fast check required',
  },
  {
    id: 'q3',
    patientId: 'p2',
    patientName: 'Priya Singh',
    patientPhone: '+91 91234 56789',
    dentistId: 'u1',
    doctorName: 'Dr. Aryan Sharma',
    scheduledTime: '11:15 AM',
    waitingMinutes: 0,
    stage: 'SCHEDULED',
    treatmentType: 'Nightguard Delivery',
  },
  {
    id: 'q4',
    patientId: 'p4',
    patientName: 'Neha Gupta',
    patientPhone: '+91 99887 66554',
    dentistId: 'u1',
    doctorName: 'Dr. Aryan Sharma',
    scheduledTime: '12:00 PM',
    waitingMinutes: 0,
    stage: 'SCHEDULED',
    treatmentType: 'Routine Scaling & Polish',
  },
];

// Mock Clinical Consumable Items
export const mockConsumables: ConsumableItem[] = [
  {
    id: 'cons1',
    dentistId: 'u1',
    name: '3M Filtek Z350 XT Composite (Shade A2)',
    category: 'RESTORATIVE',
    brand: '3M ESPE',
    sku: '3M-Z350-A2',
    currentStock: 3,
    minThreshold: 5,
    unit: 'Syringes (4g)',
    costPerUnit: 1850,
    expiryDate: '2027-04-30',
    supplierName: 'DentCart India',
    location: 'Cabinet 2 - Drawer A',
    lastRestocked: '2026-07-15',
  },
  {
    id: 'cons2',
    dentistId: 'u1',
    name: 'Lignocaine 2% with Adrenaline 1:80000',
    category: 'SURGICAL',
    brand: 'Septodont (Lignospan)',
    sku: 'SEP-LIGNO-50',
    currentStock: 82,
    minThreshold: 30,
    unit: 'Cartridges (1.8ml)',
    costPerUnit: 35,
    expiryDate: '2027-11-30',
    supplierName: 'MedTech Supplies',
    location: 'Operatory Anesthetic Safe',
    lastRestocked: '2026-08-01',
  },
  {
    id: 'cons3',
    dentistId: 'u1',
    name: 'ProTaper Gold Rotary Files Assorted (25mm)',
    category: 'ENDODONTICS',
    brand: 'Dentsply Sirona',
    sku: 'DEN-PTG-AST',
    currentStock: 2,
    minThreshold: 4,
    unit: 'Packs (6 files)',
    costPerUnit: 2400,
    expiryDate: '2029-01-01',
    supplierName: 'DentCart India',
    location: 'Endo Tray Rack 1',
    lastRestocked: '2026-06-20',
  },
  {
    id: 'cons4',
    dentistId: 'u1',
    name: 'GC Gold Label 9 Extra GIC Radiopaque',
    category: 'RESTORATIVE',
    brand: 'GC Corp',
    sku: 'GC-GL9-15G',
    currentStock: 6,
    minThreshold: 3,
    unit: 'Boxes',
    costPerUnit: 1650,
    expiryDate: '2028-02-28',
    supplierName: 'Dental Direct',
    location: 'Cabinet 1 - Shelf B',
    lastRestocked: '2026-07-28',
  },
  {
    id: 'cons5',
    dentistId: 'u1',
    name: 'Nitrile Examination Gloves (Powder-Free M)',
    category: 'PPE_DISPOSABLES',
    brand: 'Kranium Safe',
    sku: 'PPE-GLV-M',
    currentStock: 18,
    minThreshold: 10,
    unit: 'Boxes (100 pcs)',
    costPerUnit: 420,
    expiryDate: '2029-06-30',
    supplierName: 'MedTech Supplies',
    location: 'Central Storage Room',
    lastRestocked: '2026-08-05',
  },
  {
    id: 'cons6',
    dentistId: 'u1',
    name: 'Metapaste Calcium Hydroxide with Barium Sulfate',
    category: 'ENDODONTICS',
    brand: 'Meta Biomed',
    sku: 'META-PST-2G',
    currentStock: 1,
    minThreshold: 3,
    unit: 'Syringes',
    costPerUnit: 1100,
    expiryDate: '2027-09-15',
    supplierName: 'DentCart India',
    location: 'Endo Tray Rack 2',
    lastRestocked: '2026-05-12',
  },
];

// Mock Consumable Inventory Movements
export const mockInventoryMovements: InventoryMovement[] = [
  {
    id: 'mov1',
    itemId: 'cons1',
    itemName: '3M Filtek Z350 XT Composite (Shade A2)',
    movementType: 'PROCEDURE_USE',
    quantity: 1,
    previousStock: 4,
    newStock: 3,
    patientId: 'p2',
    visitId: 'v3',
    reason: 'Direct Composite Aesthetic Bonding #11',
    timestamp: '2026-08-12T15:30:00Z',
    performedBy: 'Dr. Aryan Sharma',
  },
  {
    id: 'mov2',
    itemId: 'cons2',
    itemName: 'Lignocaine 2% with Adrenaline 1:80000',
    movementType: 'PROCEDURE_USE',
    quantity: 2,
    previousStock: 84,
    newStock: 82,
    patientId: 'p1',
    visitId: 'v1',
    reason: 'Inferior Alveolar Nerve Block #36',
    timestamp: '2026-08-10T10:15:00Z',
    performedBy: 'Dr. Aryan Sharma',
  },
  {
    id: 'mov3',
    itemId: 'cons5',
    itemName: 'Nitrile Examination Gloves (Powder-Free M)',
    movementType: 'STOCK_IN',
    quantity: 10,
    previousStock: 8,
    newStock: 18,
    reason: 'Monthly Restock PO #88912',
    timestamp: '2026-08-05T09:00:00Z',
    performedBy: 'Clinic Admin',
  },
];

// Mock Invoices & Billing Records
export const mockInvoices: ClinicalInvoice[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-0042',
    patientId: 'p1',
    patientName: 'Rahul Sharma',
    dentistId: 'u1',
    visitId: 'v1',
    items: [
      { id: 'li1', description: 'Root Canal Therapy (Molar #36)', toothNumber: 36, unitPrice: 4500, quantity: 1, discount: 0, total: 4500 },
      { id: 'li2', description: 'Digital RVG Diagnostic X-Rays (2 Views)', unitPrice: 350, quantity: 2, discount: 0, total: 700 },
      { id: 'li3', description: 'Monolithic Zirconia Crown (Advance Export)', toothNumber: 14, unitPrice: 6500, quantity: 1, discount: 500, total: 6000 },
    ],
    subtotal: 11700,
    discountTotal: 500,
    taxTotal: 0,
    grandTotal: 11200,
    paidAmount: 8000,
    balanceAmount: 3200,
    paymentStatus: 'PARTIAL',
    paymentMethod: 'UPI',
    dueDate: '2026-08-25',
    createdAt: '2026-08-10T11:45:00Z',
    notes: 'Advance Rs 8,000 paid via GPay. Balance Rs 3,200 due on crown cementation.',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-0043',
    patientId: 'p2',
    patientName: 'Priya Singh',
    dentistId: 'u1',
    visitId: 'v3',
    items: [
      { id: 'li4', description: 'Multi-layer Anterior Aesthetic Composite Bonding #11', toothNumber: 11, unitPrice: 3500, quantity: 1, discount: 0, total: 3500 },
      { id: 'li5', description: 'Custom Nightguard Soft/Hard Double Laminate', unitPrice: 4000, quantity: 1, discount: 500, total: 3500 },
    ],
    subtotal: 7500,
    discountTotal: 500,
    taxTotal: 0,
    grandTotal: 7000,
    paidAmount: 7000,
    balanceAmount: 0,
    paymentStatus: 'PAID',
    paymentMethod: 'CARD',
    dueDate: '2026-08-12',
    createdAt: '2026-08-12T16:00:00Z',
    paidAt: '2026-08-12T16:05:00Z',
    notes: 'Full payment cleared via HDFC Credit Card.',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2026-0044',
    patientId: 'p3',
    patientName: 'Amit Patel',
    dentistId: 'u1',
    items: [
      { id: 'li6', description: 'Titanium Dental Implant Placement #30 (Nobel Biocare)', toothNumber: 30, unitPrice: 28000, quantity: 1, discount: 2000, total: 26000 },
      { id: 'li7', description: 'Custom Titanium Milled Abutment & Screw-Retained Crown', toothNumber: 30, unitPrice: 11500, quantity: 1, discount: 0, total: 11500 },
    ],
    subtotal: 39500,
    discountTotal: 2000,
    taxTotal: 0,
    grandTotal: 37500,
    paidAmount: 25000,
    balanceAmount: 12500,
    paymentStatus: 'PARTIAL',
    paymentMethod: 'NETBANKING',
    dueDate: '2026-08-30',
    createdAt: '2026-08-08T12:00:00Z',
    notes: 'Initial surgical deposit paid. Remaining balance due on prosthetic delivery.',
  },
];

export const mockCases: Case[] = [
  {
    id: 'c1',
    patientId: 'p1',
    patientName: 'Rahul Sharma',
    dentistId: 'u1',
    labId: 'lab1',
    status: 'IN_PROGRESS',
    urgency: 'HIGH',
    requestedTreatment: 'Zirconia Crown (Tooth 14)',
    material: 'Zirconia HT',
    createdAt: '2026-08-01T10:00:00Z',
    dueDate: '2026-08-18T10:00:00Z',
    shade: 'A2',
    selectedTeeth: [14],
  },
  {
    id: 'c2',
    patientId: 'p2',
    patientName: 'Priya Singh',
    dentistId: 'u1',
    labId: 'lab1',
    status: 'QUALITY_CHECK',
    urgency: 'NORMAL',
    requestedTreatment: 'Lower Arch Nightguard',
    material: 'Dual Laminate Acrylic',
    createdAt: '2026-08-08T09:30:00Z',
    dueDate: '2026-08-18T10:00:00Z',
    shade: 'Clear',
  },
  {
    id: 'c3',
    patientId: 'p3',
    patientName: 'Amit Patel',
    dentistId: 'u1',
    labId: 'lab1',
    status: 'PENDING',
    urgency: 'URGENT',
    requestedTreatment: 'Porcelain Veneers (Teeth 11, 21)',
    material: 'E.max CAD Shade A1',
    createdAt: '2026-08-14T08:00:00Z',
    dueDate: '2026-08-28T10:00:00Z',
    shade: 'A1 Bleach',
    selectedTeeth: [11, 21],
  },
  {
    id: 'c4',
    patientId: 'p4',
    patientName: 'Neha Gupta',
    dentistId: 'u1',
    labId: 'lab1',
    status: 'DELIVERED',
    urgency: 'LOW',
    requestedTreatment: 'Implant Abutment (Tooth 30)',
    material: 'Titanium Grade V',
    createdAt: '2026-05-25T14:20:00Z',
    dueDate: '2026-06-05T10:00:00Z',
    selectedTeeth: [30],
  },
];

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: 't1',
    caseId: 'c1',
    statusUpdate: 'IN_PROGRESS',
    notes: 'Digital STL scanned and validated. Milling path generated on 5-axis Roland milling machine.',
    timestamp: '2026-08-02T14:00:00Z',
    visibility: 'BOTH',
  },
  {
    id: 't2',
    caseId: 'c1',
    statusUpdate: 'PENDING',
    notes: 'Case uploaded by Dr. Aryan Sharma with IOS scan files.',
    timestamp: '2026-08-01T10:00:00Z',
    visibility: 'BOTH',
  },
];

export const mockLabProfiles: LabProfile[] = [
  {
    id: 'lab1',
    name: 'Advance Dental Export',
    rating: 4.9,
    reviewsCount: 148,
    services: ['Zirconia Multilayer', 'Custom Titanium Abutments', 'E.max Veneers', 'Nightguards'],
    pricing: '$$',
    turnaroundTime: '3-5 Business Days',
    contactEmail: 'orders@advancedentalexport.in',
    contactPhone: '+91 80 4123 4567',
  },
  {
    id: 'lab2',
    name: 'Kanpur Dental CAD Lab',
    rating: 4.8,
    reviewsCount: 92,
    services: ['High-End Ceramics', 'Digital Smile Design', 'Surgical Guides'],
    pricing: '$$$',
    turnaroundTime: '5-7 Business Days',
    contactEmail: 'contact@kanpurdentallab.com',
    contactPhone: '+91 512 234 5678',
  },
  {
    id: 'lab3',
    name: 'Vaishali Milling Center',
    rating: 4.6,
    reviewsCount: 210,
    services: ['Zirconia Copings', 'Screw-Retained Bridges', 'Surgical Guides'],
    pricing: '$',
    turnaroundTime: '2-3 Business Days',
    contactEmail: 'milling@vaishalidental.in',
    contactPhone: '+91 120 456 7890',
  },
];

export const mockInventory: InventoryItem[] = [
  { id: 'inv1', labId: 'lab1', name: 'Zirconia 3D Pro Multilayer Disc 98mm', category: 'Milling Discs', quantity: 18, threshold: 5, unit: 'discs' },
  { id: 'inv2', labId: 'lab1', name: 'IPS e.max CAD HT Blocks (Shade A1/A2)', category: 'Blocks', quantity: 4, threshold: 10, unit: 'blocks' },
  { id: 'inv3', labId: 'lab1', name: 'NextDent Model 2.0 3D Print Resin 1kg', category: '3D Printing', quantity: 12, threshold: 4, unit: 'bottles' },
  { id: 'inv4', labId: 'lab1', name: 'Pre-milled Titanium Abutment Blanks', category: 'Implant Components', quantity: 35, threshold: 15, unit: 'pieces' },
];

export const mockDoctorInventory: DoctorInventoryItem[] = [
  {
    id: 'di1',
    dentistId: 'u1',
    labId: 'lab1',
    materialName: 'Zirconia HT Monolithic Block Credit',
    totalUnits: 100,
    remainingUnits: 94,
    lockedPrice: '₹2,450 / unit',
  },
  {
    id: 'di2',
    dentistId: 'u1',
    labId: 'lab1',
    materialName: 'IPS e.max Lithium Disilicate Credit',
    totalUnits: 50,
    remainingUnits: 46,
    lockedPrice: '₹3,200 / unit',
  },
];

export const mockOrderChats: OrderChat[] = [
  {
    id: 'chat1',
    caseId: 'c1',
    messages: [
      {
        id: 'm1',
        chatId: 'chat1',
        senderId: 'u1',
        content: 'Hi Advance Dental, please ensure light interproximal contacts and a deep chamfer margin for tooth 14.',
        timestamp: '2026-08-01T11:00:00Z',
      },
      {
        id: 'm2',
        chatId: 'chat1',
        senderId: 'u2',
        content: 'Confirmed Dr. Sharma. 3D scan quality is excellent. 5-axis milling is scheduled for this afternoon.',
        timestamp: '2026-08-01T11:20:00Z',
      },
    ],
  },
];
